// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/8/2025, 2:28:52 PM
const configMerger = require("/Users/emmahons/Documents/mind 2/BSLB/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/emmahons/Documents/mind 2/BSLB/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/plugins/**/*.{js,ts,mjs}","/Users/emmahons/Documents/mind 2/BSLB/composables/**/*.{js,ts,mjs}","/Users/emmahons/Documents/mind 2/BSLB/utils/**/*.{js,ts,mjs}","/Users/emmahons/Documents/mind 2/BSLB/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/emmahons/Documents/mind 2/BSLB/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
